### PR TITLE
mongo-sys msvc support

### PR DESCRIPTION
**Pull request by inv2004**
It can work with vcpkg or via manual setting env vars MONGO_LIB and BSON_LIB

dylib only.

### CODE REVIEW

**Comment by inv2004** [comment]
@thijsc

**Comment by thijsc** [comment]
Thanks for you contribution!

I have no way to verify this works since I don't own any Windows computers. Could we set up a Windows CI build? I think appveyor does this?

**Comment by inv2004** [comment]
I have never tried appveyor, but it should work. But I suppose the only important for now - to check that linux-build is not broken.

**Comment by thijsc** [comment]
I think that if we merge this there should be CI for it. Otherwise I have no way to know if I accidentally break it. I only want to add code that's covered by tests in a CI.

Do you have some time to take a stab at this?

**Comment by inv2004** [comment]
let me try.

**Comment by ayosec** [comment]
> Could we set up a Windows CI build? I think appveyor does this?

Travis supports Windows.

https://docs.travis-ci.com/user/reference/windows/

**Comment by inv2004** [comment]
@thijsc 
please find appveyor is done and it works. badge is up to you.

test_ssl_connection_success fails, but not sure if its related to windows.

**Comment by inv2004** [comment]
test_ssl_connection_success probably related to openssl*.dll I will check it.

**Comment by thijsc** [comment]
There is actually a note on this in the readme: https://github.com/thijsc/mongo-rust-driver#ssl-test

**Comment by inv2004** [comment]
I am waiting for https://github.com/Microsoft/vcpkg/pull/4722

**Comment by inv2004** [comment]
test database.command and collection.command fails in core in mongoc_cursor_destroy(...)

**Comment by thijsc** [comment]
Where can I see the output of that build?

**Comment by inv2004** [comment]
@thijsc 
I have sent invitation to your email from appveyor.

**Comment by thijsc** [comment]
Good results so far, it's all building properly. The point where the tests fail:

```
running 39 tests
393test bulk_operation::test_basics ... ok
394test bson_encode_decode::test_bson_encode_decode ... ok
395test bulk_operation::test_execute_error ... ok
396test bulk_operation::test_utf8 ... ok
397test bulk_operation::test_insert_remove_replace_update_extended ... ok
398test client::test_new_pool_and_pop_client_in_threads ... ok
399test client::test_new_pool_pop_client_and_borrow_collection ... ok
400test client::test_new_pool_pop_client_and_take_collection ... ok
401test client::test_new_pool_pop_client_and_take_database_and_collection ... ok
402test client::test_new_pool_with_ssl_options ... ok
403test client::test_get_server_status ... ok
404test client::test_ssl_connection_success ... ok
405test client::test_ssl_options_nonexistent_file ... ok
406test client::test_read_command_with_opts ... ok
407test collection::test_aggregate ... ok
408test collection::test_command_simple ... ok
409test collection::test_find_and_modify ... ok
410test collection::test_insert_failure ... ok
411error: test failed, to rerun pass '--test tests'
412Command exited with code -1073740940
```
It doesn't say what the error is. Is there a way to get that output?

**Comment by thijsc** [comment]
@inv2004 can you push something? I've added a public appveyor here.

**Comment by inv2004** [comment]
It all output we have + I have the same on local machine.
-1073740940 is the exit code from the binary, Its the same like STATUS_HEAP_CORRUPTION or Access violation +core in linux . If I comment mongoc_cursor_destroy - everything is ok.

**Comment by inv2004** [comment]
dbgx shell_2018-12-13_22-57-28


windbg shows it.
I suppose no reasons to debug deeper, because I see the place was changed in newer mongoc-driver, unfortunately its necessary to change ffi to support something >1.9.5. Thats why I would recommend to disable the 2-3 tests for windows.

**Comment by inv2004** [comment]
appveyor test is passed. I suppose its the best we can do it the moment.

Also, I found the the place in mongo-c-driver is not the same as in 1.10.0 and not the same as 1.8.2 (but its does not support change-stream), it could explain why it does not fail on linux at the moment.

**Comment by thijsc** [comment]
Awesome to see that you got a green build! I'm merging this, we should reenable the tests on the mongoc upgrade.

**Pull request merged**
