### PR TITLE
add CLANG_INCLUDE_DIR environment hacks

### PR DESCRIPTION
**Pull request by zerosign**
- Some linux distro just can't detect correctly clang default include path when building using
  rust-bindgen.

### CODE REVIEW

**Comment by thijsc** [comment]
Thanks for the pull!

`/usr/lib/clang/3.6.1/include` does not exist on my system, why is that a sensible default path? Maybe we could just add no arguments if the env var is not set?

**Comment by zerosign** [comment]
Ok, done

**Comment by thijsc** [comment]
I looked into this a bit more. Seems like they're trying to fix this in bindgen itself. See https://github.com/crabtw/rust-bindgen/commit/e9b2f7a2d401edf6b7662b187bd415253b072df5 for example. Maybe we should try to leverage that solution? Or did you try that and it didn't work?

**Comment by zerosign** [comment]
Hmm, It still didn't work quite well (seems related to clang issue finding stdef in my case or rather related to specific distros issue (archlinux in my case)). I'll try to lookup into bindgen code, but for a moment this "hacks" could also quite useful at least for windows users since their clang path will be quite hard to find depends on how they install it. 

Thanks.

**Comment by thijsc** [comment]
I made a slightly different fix here: f18fde5c77291b2e0d23fe1f9b24686e9d957f1f

This adds the include path that bindgen tries to find as well as the environment var you proposed. I think this might solve the issue without resorting to a env var. Could you try compiling without it on your system?

**Comment by zerosign** [comment]
it seem works :+1:

**Comment by thijsc** [comment]
Cool!

**Pull request closed without merging**
