### PR TITLE
added mongoc_client_read_command_with_opts

### PR DESCRIPTION
**Pull request by mjjansen**
to be able to run collStats and other commands

### CODE REVIEW

**Comment by thijsc** [comment]
Looks good! Can you rebase so there's no redundant merge commit?

**Comment by mjjansen** [comment]
I did a rebase, but I think I made it worse.  let me know if there's a simple command to this easily.  thank you.

**Comment by thijsc** [comment]
Ahm yeah :-). Maybe just cherry-pick your own commit to a new branch and force push that over this? Otherwise I can also close this pull and just cherry-pick the commit into `master`.

**Comment by mjjansen** [comment]
good?

**Review by thijsc — APPROVED** [review]

**Pull request merged**
